# Site settings
title: palimedia
email: office.palimedia@gmail.com
phone: +43 664 9159998
url: https://palimedia.at
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "Multimedia-Agentur<br>Web - Logo - 3D - Fotografie - Video"
meta_author: Pali Adrian, palimedia.at

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: F15A29 #80B3FF
  primary-rgb: "241,90,41" #"128,179,255"
  secondary: 262A33 #FD6E8A
  secondary-dark: 1b1e24 #A2122F

# Footer settings
footer:
  copyright: palimedia.at e.U.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: facebook
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: twitter
    url: http://twitter.com/palimedia
  - title: github
    url: http://github.com/palimedia

# Postal address (add as many lines as necessary)
address:
  - line: 6382 Kirchdorf in Tirol
  - line: Sensenschmiedweg 20

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
