# Site settings
title: Salon Adelsberger Barbara
email: hundefriseurin90@gmail.com
description: Hundefriseurin Adelsberger Barbara  # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://www.hundefriseurin-adelsberger.at" # the base hostname & protocol for your site

telephone: +43 664 577 567 6
adress: Unterm Rain 1<br>6382 Kirchdorf in Tirol

# Build settings
markdown: kramdown
