# Site settings
title: Salon Adelsberger Barbara
email: info@salon-adelsberger.at
description: Hundefriseurin Adelsberger Barbara  # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://www.salon-adelsberger.at" # the base hostname & protocol for your site

telephone: +43 664 915 999 8
adress: Sensenschmiedweg 20<br>6382 Kirchdorf in Tirol

# Build settings
markdown: kramdown
