# Site settings
title: Salon Adelsberger Barbara
email: info@salon-adelsberger.at
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.salon-adelsberger.at" # the base hostname & protocol for your site

twitter_username: adrian.pali
github_username: adrian.pali

# Build settings
markdown: kramdown
