# Site settings
title: Hundefriseurin Adelsberger
email: hundefriseurin90@gmail.com
description: Das Wohl des Tieres steht an oberster Stelle. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.hundefriseurin-adelsberger.at" # the base hostname & protocol for your site

name: Adelsberger Barbara
profession: Hundefriseurin
telephone: +43 664 577 567 6
address_street: Unterm Rain 1
address_code: 6382
address_locality: Kirchdorf in Tirol

# Build settings
markdown: kramdown
